INSERT INTO equipments (equ_name, equipment_type_id, equ_status, equ_availability)
VALUES 
('Cable Crossover', 3, true, true),
('Barbell Rack', 4, false, false),
('Glute-Ham Developer', 2, true, true),
('Incline Bench Press', 1, true, true),
('Leg Curl Machine', 2, false, false),
('Seated Leg Press', 2, true, true),
('Lat Pulldown Machine', 3, true, true),
('EZ Curl Bar', 4, true, true),
('Battle Ropes', 5, true, true),
('Resistance Bands', 5, true, true),
('Treadmill', 1, true, true),
('Elliptical', 1, true, true),
('Stationary Bike', 1, true, true),
('Rowing Machine', 1, true, true),
('Stair Climber', 1, true, true),
('Weight Bench', 2, true, true),
('Dumbbells', 2, true, true),
('Barbell', 2, true, true),
('Kettlebells', 2, true, true),
('Resistance Bands', 2, true, true),
('Yoga Mats', 3, true, true),
('Pilates Reformer', 3, true, true),
('Exercise Ball', 3, true, true),
('Foam Roller', 3, true, true),
('Jump Rope', 3, true, true),
('Climbing Rope', 4, true, true),
('Pull-up Bar', 4, true, true),
('Parallel Bars', 4, true, true),
('Squat Rack', 4, true, true),
('Weighted Vest', 4, true, true);
